### ISSUE TITLE
Update images to reflect new UI changes

### ISSUE THREAD

**Issue by ChunkyProgrammer** [FreeTubeApp/FreeTubeApp.io#14]
Ex: trending page now has 3 tabs
Search bar has the clear button
Theatre mode was moved to inside the player

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
hi @ChunkyProgrammer what do u think about these screenshots. Im not able to make them that big as the original ones :( 
![signal-2022-04-23-185031_001](https://user-images.githubusercontent.com/73130443/164915714-0a1cdc0b-e02b-4ede-97e9-3793cdc9eea5.jpeg)
![signal-2022-04-23-184803_001](https://user-images.githubusercontent.com/73130443/164915717-77a711c4-9bb0-434f-9702-25e7069d08c7.jpeg)
![signal-2022-04-23-184803_002](https://user-images.githubusercontent.com/73130443/164915718-a7523588-026a-4044-b258-a9ca3b61c0b2.jpeg)

I will cut out the taskbar if u think these are good pictures.
