### ISSUE TITLE
freetubeapp.io: HTTPS Certificate Expired

### ISSUE THREAD

**Issue by AwlsomeAlex** [FreeTubeApp/FreeTubeApp.io#16]
Your certificate expired...
"This Connection is Not Private"
Expired: Thursday, May 12, 2022 at 10:05:52 PM Eastern

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Will be fixed within a week. Thanks for letting us know!

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Its fixed!
