### ISSUE TITLE
bug: site header is broken in Mozilla browser 

### ISSUE THREAD

**Issue by nikpivkin** [FreeTubeApp/FreeTubeApp.io#34]
<img width="1414" alt="image" src="https://github.com/FreeTubeApp/FreeTubeApp.io/assets/100182843/0a165955-515d-4232-83a9-89ee3e88ee3f">

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Dont seem to be broken on my end

**Comment by nikpivkin** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc Is it in the Mozilla browser?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Yup Firefox

**Comment by nikpivkin** [comment]
Strangely
