### ISSUE TITLE
Menu bar but no window, macOS Catalina

### ISSUE THREAD

**Issue by Tonym69** [FreeTubeApp/FreeTubeApp.io#43]
After a few days of happy use now can't get any window to appear. Menu bar is present. 

Successively tried ditching plist, restart Mac, uninstall FreeTube and related files (using AppCleaner) and re-download and reinstall but still no joy. 

Version 0.20.0

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Try using f11

**Comment by Tonym69** [comment]
Show desktop on Mac – is that what you meant?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Um not sure if thats it. I only know that this bug can be solved by pressing  f11. That will show the top bar again

**Comment by Tonym69** [comment]
Top bar is good but I can't get any window to appear. Doesn't do it when it's opened and doesn't do it when I CMD+N or choose "New Window" – still no window.

**Comment by pranavburnwal** [comment]
If any one Stumbles on this. Basically, your Winowd has 'shrunk' to pixel somehow. 
Press f11 and then you should see freetube icon somewhere in the corner. Try to move your cursor and the Curso will become arrow like 'expand' your window. DO that and it will be back.
